### PR TITLE
Clarify drive multiplier

### PR DESCRIPTION
**Pull request by tabiosg**
The driver multiplier currently may look confusing and may seem like a magic number. It may be better to just change the multiplier in the config to a number that directly represents the conversion from 
1. turns to meters and 
2. that converts desired -1.0 to 1.0 to either desired turns or to desired meters (probably meters since it's more intuitive?).

Like this is better because it makes the config easier to read for any user.

### CODE REVIEW

**Comment by tabiosg** [comment]
@sashreek1 @wilsonchen02 hey can both of you review this asap? this one is kinda important... i want to make sure that i did NOT do my math wrong by making this change. just assume that the previous code was correct (this PR shouldn't change any behavior).

Summary of code: Basically changing the conversions.

Previously we had 
multiplier:
    vel_cmd_multiplier_left: 50
    vel_cmd_multiplier_right: -50
    vel_est_multiplier_left: -0.02513
    vel_est_multiplier_right: 0.02513


Now we have
  ratio:
    meters_to_turns_ratio_left: -39.793
    meters_to_turns_ratio_right: 39.793
    meters_to_raw_ratio_left: -1989.0
    meters_to_raw_ratio_right: 1989.0

I got 39.793 by doing 1 / 0.02513 = 39.793. 
I got 1989.0 by doing 50 * 39.793.

**Comment by wilsonchen02** [comment]
> Summary of code: Basically changing the conversions.
> 
> Previously we had multiplier: vel_cmd_multiplier_left: 50 vel_cmd_multiplier_right: -50 vel_est_multiplier_left: -0.02513 vel_est_multiplier_right: 0.02513
> 
> Now we have ratio: meters_to_turns_ratio_left: -39.793 meters_to_turns_ratio_right: 39.793 meters_to_raw_ratio_left: -1989.0 meters_to_raw_ratio_right: 1989.0
> 
> I got 39.793 by doing 1 / 0.02513 = 39.793. I got 1989.0 by doing 50 * 39.793.

To clarify, is 0.02513 the number of turns per meter? And so 1 turn is 39.793 meters?
I don't really get the x50 part but I assume that's just what it is for raw numbers

Edit: also 
image
Not sure if it needs to be this accurate but this is without rounding early

**Review by wilsonchen02 — APPROVED** [review]
image
understandable

**Comment by tabiosg** [comment]
> To clarify, is 0.02513 the number of turns per meter? And so 1 turn is 39.793 meters? I don't really get the x50 part but I assume that's just what it is for raw numbers

So um I think 0.02513 was the number of turns per meter. I'm not too sure. What I did notice in the old code was that in order to get our results in meters/second, we were apparently multiplying 0.02513 to the raw data being given from the odrive so I think it is? Basically the Odrive gave it in turns/second, and then we multiply that number by 0.02513meters/turn, and then we get meters/second. 

1 turn is apparently 39.793 meters which DOES NOT make sense though because there is no way the circumference of our wheels is 39.793 meters (is rosie secretely a demolition derby???!!??!)

Also yes the 50 is kinda arbitrary I think, it was also based on our testing (maybe i should keep the 50 number now that I think about it since I just realized that we came up with that number by testing).

**Comment by tabiosg** [comment]
Also yea about the rounding early part, I was thinking about double checking the math but I think the small error is negligible lol

**Comment by sashreek1** [comment]
Some of these numbers don't make sense at all. But if the old code worked, I think this should be fine

**Comment by tabiosg** [comment]
Yikes its not good that we don't know why it worked lol

**Comment by tabiosg** [comment]
Ok i think what happened is that our turns to meters ratio is just flat out wrong. I think I'll reintroduce the turns to raw configuration (instead of meters to raw) since we know that for sure works. Maybe the published data was always wrong but we didn't care since it doesn't affect our inputs

**Pull request merged**
