### PR TITLE
Store videoSource reference instead of making copy

### PR DESCRIPTION
**Pull request by tabiosg**
[IMPORTANT] So right now in the code, each Pipeline object makes a copy of the videoSource object, which is NOT what we want. If the videoSource object changes in the PipelineManager, we want it to to change in the Pipeline too.

The fix is to just instead assign the list from the PipelineManager to the Pipeline once and then we don't need to worry again. When you assign a list to variable, it treats the variable as a pointer to the list.

ALSO: It would be very useful to include in documentation that the two videoSource Lists point to the same space in memory so nobody is confused why changes to one list/variable affects the other.

### CODE REVIEW

**Comment by tabiosg** [comment]
@wilsonchen02 code is ready, idk if code is worse (to read) now though, it's kinda confusing since now the user will have to keep track of how the videosources are being modified and how the numbers are changing

**Comment by wilsonchen02** [comment]
> @wilsonchen02 code is ready, idk if code is worse (to read) now though, it's kinda confusing since now the user will have to keep track of how the videosources are being modified and how the numbers are changing

Agree with it being more confusing now

**Comment by tabiosg** [comment]
i actually changed it so it's less confusing...

**Comment by tabiosg** [comment]
by passing it as a parameter

**Review by wilsonchen02 — APPROVED** [review]
understandable

image

**Pull request merged**
