### PR TITLE
Add cameras software requirements

### PR DESCRIPTION
**Pull request by tabiosg**
Update software requirements on this file: https://github.com/tabiosg/mrover-ros/tree/add_cameras_requirements/src/esw/cameras#readme

### CODE REVIEW

**Comment by tabiosg** [comment]
This PR is intended to add the software requirements for the cameras to the README.md.

The software requirements should be anything that the program should be able to do. A draft for the section was made in the README.md.

@wilsonchen02: you can add anything that you see already exists in the code or anything that you think the cameras program should be capable of doing. Better to write more requirements and be as specific as possible.

This PR is useful so anybody reading this project knows what the program should be capable of doing AND so we can formulate unit tests based on these requirements.

**Comment by tabiosg** [comment]
Ideas of requirements to add would be stuff like "Program never exceeds total bandwidth of 1,500,000 bps" or something more reasonable (for this example, I'm actually not sure what a good number is but I guess you can put a dummy number and add a note)

**Comment by tabiosg** [comment]
Here are some useful links:

ESW Wiki (cameras section): https://github.com/umrover/mrover-ros/wiki/ESW#cameras
Cameras PR into main: https://github.com/umrover/mrover-ros/pull/49
This year's camera README: https://github.com/tabiosg/mrover-ros/tree/cameras_ros/src/esw/cameras#project-overview
Last year's official camera code (used for URC): https://github.com/umrover/mrover-workspace/blob/main/jetson/cameras/src/__main__.py#L172
This year's camera code: https://github.com/tabiosg/mrover-ros/blob/cameras_ros/src/esw/cameras/cameras.py

**Comment by tabiosg** [comment]
BTW, the requirements section does not have to be long. It could be like about 20 bullet points or less. The main hope is that it is testable and that it accurately represents what the cameras program is expected to be able to do.

**Review by wilsonchen02 — APPROVED** [review]

**Pull request merged**
