### PR TITLE
Add assertions

### PR DESCRIPTION
**Pull request by tabiosg**
Add all the assertions that one could possibly think of.

### CODE REVIEW

**Comment by wilsonchen02** [comment]
Do we need to assert that an IP is valid? If so, how? Can current_ip be an empty string?
image

**Comment by wilsonchen02** [comment]
image
This section is a little odd because it the returned item is a string not a list of strings

**Comment by tabiosg** [comment]
> Do we need to assert that an IP is valid? If so, how? Can current_ip be an empty string? image

good question... yea i think we should assert that current_ip is not an empty string, could u make that addition for me?

**Comment by tabiosg** [comment]
lmk if u think it's ready

**Pull request merged**
